groups:
  - name: klaytn-node-alert
    rules:
    - alert: klaytn-node-down
      expr: up{class="klaytn-rpc-node"} == 0
      for: 1m
      labels:
        severity: warn
      annotations: 
        summary: "Klaytn Endpoint Node not responding"  
        description: "- instance: {{ $labels.instance }} \n- name: {{ $labels.name }} Klaytn Endpoint Node keeps not responding more than 1 mi" 
        value: "{{ $value }}"
        instance: "{{ $labels.instance }}"
        id: "{{ $labels.instanceid }}"
  - name: HyperNode-node-alert
    rules:
    - alert: HyperNode-node-down
      expr: up{class="HyperNode"} == 0
      for: 1m
      labels:
        severity: warn
      annotations: 
        summary: "HyperNode not responding"  
        description: "- instance: {{ $labels.instance }} \n- name: {{ $labels.name }} HyperNode keeps not responding more than 1 min" 
        value: "{{ $value }}"
        instance: "{{ $labels.instance }}"
        id: "{{ $labels.instanceid }}"
